### ISSUE TITLE
tokenBucket: incorrect count of issued when refill

### ISSUE THREAD

**Issue by rschio** [reugn/equalizer#6]
https://github.com/reugn/equalizer/blob/d5d1ad141fc658bfb6bd994ebf5cfcd09d351dc5/token_bucket.go#L66-L79

A token can be issued between line 68 and 69 and then it will lead to a incorrect issued count and decrease the bucket real capacity.

Example:
refill() and Ask() executes concurrently then:
line 68 executes
line 77 and 78 executes
line 69 and 70 executes

Solution: 
`issued := atomic.SwapInt32(&tb.issued, 0)`

**Comment by reugn** [comment]
@rschio thanks.
