### ISSUE TITLE
Maybe consider context.Context for blocking Take()

### ISSUE THREAD

**Issue by lotodore** [reugn/equalizer#7]
Thanks for providing this simple library!
One thing I noted is that `Take()` cannot be interrupted if it takes very long (some api limits are very strict), so for example it will considerably delay aborting an action. Could you maybe consider to provide a Take operation which can be interrupted through a context object? That would be a great improvement!

**Comment by reugn** [comment]
Thanks, @lotodore. A context parameter has been added to the blocking call in [v0.2.0](https://github.com/reugn/equalizer/releases/tag/v0.2.0).
